### PR TITLE
Pull in upstream updates

### LINKED ISSUE #1: Pull in updates from cisagov/skeleton-tf-module
# 💡 Summary #

We should pull in updates from [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module).

## Motivation and context ##

This project is missing a [cisagov/action-lineage](https:/github.com/cisagov/action-lineage) so it is not getting automatic updates. This also means it does not have a configuration that supports [cisagov/action-apb](https:/github.com/cisagov/action-apb).

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull requests pulls in upstream updates from [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module).

## 💭 Motivation and context ##

This repository is so out of date it does not have a [cisagov/action-lineage](https://github.com/cisagov/action-lineage) configuration.

### Terraform upgrade ###

The configuration on `develop` is still for Terraform 0.12. Due to the lack of dependencies in this project I walked it through upgrades from 0.12 -> 0.13, 0.13 -> 0.14, 0.14 -> 0.15, and lastly 0.15 -> 1.0. There were some non-destructive changes in the 0.13 apply, but every successive applies were clean and the deployed configuration is now up-to-date.

### Note ###

This repository should still be modernized for how we do these projects *now*. I just wanted to make sure it was at least up-to-date with its appropriate upstream skeleton. This will resolve #1.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
Doesn't `providers.tf` need to be updated to use default tags?

**Comment by jsf9k** [comment]
This thing was more out of date than John Cena's jorts!

**Comment by mcdonnnj** [comment]
> Doesn't `providers.tf` need to be updated to use default tags?

@jsf9k I accidentally lost the `tags` variable when updating, so I saw it without and didn't add the `default_tags` pieces. Noticed that belatedly and restored the variable + added the default tags configuration in [3d3ab8a](https://github.com/cisagov/cool-users-new-user-alarm/pull/2/commits/3d3ab8ac38b19d99401e06ceb41313be31283e00).

**Comment by jsf9k** [comment]
Why is Snyk choking on `requirements-test.txt`?

**Comment by mcdonnnj** [comment]
> Why is Snyk choking on `requirements-test.txt`?

I'm not sure. The log on Snyk doesn't even agree with the test link here:

```log
Processed cisagov/cool-users-new-user-alarm from GitHub

    Found alarm.tf [develop] View project
    Found backend.tf [develop] View project
    Found locals.tf [develop] View project
    Found outputs.tf [develop] View project
    Found providers.tf [develop] View project
    Found provisionalarm_policy.tf [develop] View project
    Found provisionalarm_policy_attachment.tf [develop] View project
    Found remote_state.tf [develop] View project
    Found variables.tf [develop] View project
    Found versions.tf [develop] View project
    Found requirements-dev.txt [develop] Failed to process manifest requirements-dev.txt
    Found requirements-test.txt [develop] View project
    [develop] We found 0 supported files 

11 projects created
```

**Comment by mcdonnnj** [comment]
> > Why is Snyk choking on `requirements-test.txt`?
> 
> I'm not sure. The log on Snyk doesn't even agree with the test link here:
> 
> ```
> Processed cisagov/cool-users-new-user-alarm from GitHub
> 
>     Found alarm.tf [develop] View project
>     Found backend.tf [develop] View project
>     Found locals.tf [develop] View project
>     Found outputs.tf [develop] View project
>     Found providers.tf [develop] View project
>     Found provisionalarm_policy.tf [develop] View project
>     Found provisionalarm_policy_attachment.tf [develop] View project
>     Found remote_state.tf [develop] View project
>     Found variables.tf [develop] View project
>     Found versions.tf [develop] View project
>     Found requirements-dev.txt [develop] Failed to process manifest requirements-dev.txt
>     Found requirements-test.txt [develop] View project
>     [develop] We found 0 supported files 
> 
> 11 projects created
> ```

@jsf9k My best guess now is that `requirements.txt` is new in this pull request and when trying to parse the updated `requirements-test.txt` while checking against `develop` it's imploding in the process.

**Review by dav3r — APPROVED** [review]
Boosh! 🌀

**Review by jsf9k — APPROVED** [review]

**Pull request merged**
